name: Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint:check

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run Jest tests with coverage
        run: npm run test:coverage

      - name: Extract coverage summary
        id: extract_coverage
        run: cat coverage/coverage-summary.json

      - name: Create coverage report comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const coverageSummary = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
            const total = coverageSummary.total;

            const coverageReport = `
            ### Coverage Report
            - **Lines:** ${total.lines.pct}%
            - **Statements:** ${total.statements.pct}%
            - **Functions:** ${total.functions.pct}%
            - **Branches:** ${total.branches.pct}%
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: coverageReport
            });
