name: Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint:check

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run Jest tests with coverage
        run: npm run test:coverage

      # Replicate this https://github.com/slackapi/node-slack-sdk/blob/main/.github/workflows/ci-build.yml#L54
      # - name: upload test coverage 